### ISSUE TITLE
raspicam use version 0.1.1

### ISSUE THREAD

**Issue by YuehChuan** [ncku-ros2-research/xenobot#14]
use raspicam-0.1.1 here
https://sourceforge.net/projects/raspicam/files/
See this thread
https://github.com/cedricve/raspicam/issues/22

**Comment by oiz5201618** [comment]
@YuehChuan Thanks for the information.
The camera may be deprecated, because the navigation algorithm will be changed into lidar sensor based one.
So the new version raspicam won't be applied.
